#%RAML 1.0
title: MyAPI
version: 1.0
baseUri: http://com.foo.bar/api

types:
  Test: object
  Foo:
    type: object
    example:
      {
        "predicate": "lineItem = \"SKU\""
      }
/test:
    get:
       responses:
         200:
           body:
             application/json:
               type: Foo
               example:
                 {
                   "predicate": "lineItem = \"SKU\""
                 }
         201:
           body:
             application/json:
               type: string
               example: "foo"
    post:
       body:
         application/json:
           type: Test
           example: {
            "foo": "bar"
           }
       headers:
         FOO:
           type: string
           displayName: Foo
           required: true
       responses:
         200:
           body:
             application/json:
               type: Test
    put:
       body:
         application/json:
           type: Test
           example: {
            "foo": "bar"
           }
       responses:
         200:
           body:
             application/json:
               type: Test
/foo:
    get:
       headers:
         FOO:
           type: string
           required: true
       responses:
         200:
           body:
             application/json:
               type: Test
