#%RAML 1.0
---
title: Commercetools Importer API
version: v1
mediaType: application/json
baseUri: https://import.commercetools.com

uses:
  error: types/error.raml
  import-item: types/import-item.raml
  price-import: types/price-import.raml
  product-import: types/product-import.raml
  product-variant-import: types/product-variant-import.raml
  category-import: types/category-import.raml
  common: types/common.raml

securitySchemes:
  oauth_2_0: !include security-schemes/oauth2.raml
securedBy: [ oauth_2_0 ]

resourceTypes:
  import-resource-by-key:
    description: |
      This resource type describes the operations that can be performed for an import resource with a given key.
    uriParameters:
      key:
        description: |
          The key of the resource.
        type: string
    get:
      description: |
        Get an import item by key. This allows monitoring the progress of importing a resource withnthe given key.
      responses:
        200:
          body:
            type: import-item.ImportItem
        404:
          body:
            type: error.ErrorResponse
    delete:
      description: |
        Deletes the imported resource with the given key. This doesn't delete the corresponding import item.
        This will change the state of the corresponding import item to 'DELETING' and on successful deletion
        to 'DELETED'.
      responses:
        200:
          body:
            type: import-item.ImportItem[]

/{projectKey}:
  uriParameters:
    projectKey:
      description: The CTP project key.
      type: string
  /category:
    post:
      description: Creates or updates a batch of categories.
      body:
        type: category-import.CategoryImport[]
        examples:
          single:   !include examples/category.json
          multiple: !include examples/categories.json
      responses:
        200:
          body:
            type: import-item.ImportItem[]
    /{key}:
      type: import-resource-by-key
  /product:
    post:
      description: Creates or updates a batch of products.
      body:
        type: product-import.ProductImport[]
        examples:
          single: !include examples/product.json
      responses:
        200:
          body:
            type: import-item.ImportItem[]
    /{key}:
      type: import-resource-by-key

  /product-variant:
    post:
      description: Creates or updates a batch of product variants.
      body:
        type: product-variant-import.ProductVariantImport[]
        examples:
          single: !include examples/product-variant.json
      responses:
        200:
          body:
            type: import-item.ImportItem[]
    /{key}:
      type: import-resource-by-key

  /price:
    post:
      description: Creates or updates a batch of prices.
      body:
        type: price-import.PriceImport[]
        examples:
          single:   !include examples/price.json
          multiple: !include examples/prices.json
      responses:
        200:
          body:
            type: import-item.ImportItem[]
    /{key}:
      type: import-resource-by-key
