#%RAML 1.0
title: datetime rule

types:
  InvalidDateTime:
    type: object
    properties:
      fooDateTime: datetime
  InvalidDate:
    type: object
    properties:
      fooDate: date-only
  InvalidTime:
    type: object
    properties:
      fooTime: time-only
  InvalidDateTimeRangeFrom:
    type: object
    properties:
      fooDateTimeFrom: datetime
  InvalidDateTimeRangeTo:
    type: object
    properties:
      fooDateTimeTo: datetime
  InvalidDateTimeRangeUntil:
    type: object
    properties:
      fooDateTimeUntil: datetime
  InvalidDateRangeFrom:
    type: object
    properties:
      fooDateFrom: date-only
  InvalidDateRangeTo:
    type: object
    properties:
      fooDateTo: date-only
  InvalidDateRangeUntil:
    type: object
    properties:
      fooDateUntil: date-only
  InvalidTimeRangeFrom:
    type: object
    properties:
      fooTimeFrom: time-only
  InvalidTimeRangeTo:
    type: object
    properties:
      fooTimeTo: time-only
  InvalidTimeRangeUntil:
    type: object
    properties:
      fooTimeUntil: time-only
  FooAtDateTime:
    type: object
    properties:
      fooAt: datetime
  FooRangeDateTime:
    type: object
    properties:
      fooFrom: datetime
      fooTo: datetime
  FooRangeUntilDateTime:
    type: object
    properties:
      fooFrom: datetime
      fooUntil: datetime
  FooAtDate:
    type: object
    properties:
      fooAt: date-only
  FooRangeDate:
    type: object
    properties:
      fooFrom: date-only
      fooTo: date-only
  FooRangeUntilDate:
    type: object
    properties:
      fooFrom: date-only
      fooUntil: date-only
  FooAtTime:
    type: object
    properties:
      fooAt: time-only
  FooRangeTime:
    type: object
    properties:
      fooFrom: time-only
      fooTo: time-only
  FooRangeUntilTime:
    type: object
    properties:
      fooFrom: time-only
      fooUntil: time-only
