#%RAML 1.0
title: method post body

/categories:
  get:
  head:
/carts:
  get:
  head:
    description: "test"
/invalid:
  head:
    body:
      application/json:
        type: object
/invalid-all:
  head:
    body:
      application/json:
        type: object
      application/xml:
