#%RAML 1.0
title: name string enum rule

types:
  Foo:
    type: string
    enum:
      - bar
  Bar:
    type: string
    pattern: /a-z/
  InvalidString:
    type: string
  FooDesc:
    type: string
    description: foo
    enum:
      - bar
  BarDesc:
    type: string
    description: bar
    pattern: /a-z/
  InvalidStringDesc:
    description: invalid
    type: string
  TypeId:
    type: string
    enum:
      - foo
      - bar
  FooType:
    type: object
    properties:
      foo:
        type: TypeId
        description: Foo
        enum:
          - foo
  BarType:
    type: object
    properties:
      foo:
        type: TypeId
        description: Foo
        enum:
          - bar
  FooBarType:
    type: object
    properties:
      foo:
        type: TypeId
        description: Foo
  BarFooType:
    type: object
    properties:
      foo:
        type: string
        description: Foo
        enum:
          - bar
  BarFooStringType:
    type: object
    properties:
      foo:
        type: string
        description: Foo
