#%RAML 1.0
title: property camel case rule

types:
  Baz:
    type: object
    properties:
        validNested: string
  Bar:
    type: object
    properties:
      valid: string
      validBaz: Baz
  FooArray:
    type: object
    properties:
      validArr:
        type: string[]
  Foo:
    type: object
    properties:
      invalid:
        type: object
        properties:
            invalidNested: string
  FooArray:
    type: object
    properties:
      invalid:
        type: array
        items:
          type: object
          properties:
            invalidNested: string
