#%RAML 1.0 Library
usage: Generator annotation types.

(annotations.package): test

uses:
  annotations: annotationlibrary.raml


types:
  Foo:
    type: string
  FooDesc:
    description: test
    type: string
