#%RAML 1.0 Library
usage: Generator annotation types.

uses:
  annotations: annotationlibrary.raml


types:
  InvalidString:
    type: string
  InvalidStringDesc:
    description: invalid
    type: string
