#%RAML 1.0
title: property singular rule

types:
  Foo:
    type: object
    properties:
      invalidItems: string
      validItem: string
      /a-z/: string
      maxApplications: number
      hasChanges: boolean
