#%RAML 1.0
title: method post body

/categories:
  get:
    queryParameters:
        limit: string
        text.en: string
        inval_id: string
        inval-id: string
        inval[id]: string
        Invalid: string
