#%RAML 1.0 Library
usage: Common data types.
(generator.package): common

uses:
  generator: ../annotationTypes/test-generator.raml

types:
  Asset:
    properties:
        id:
            type: string
        tags?:
            type: string[]
