#%RAML 1.0 Library
usage: Simple type test.
(generator.package): simpleTypes

uses:
    generator: ../annotationTypes/test-generator.raml
    common: common.raml

types:
    SimpleType:
        type: common.Asset
        description: This is a test description.
        properties:
            createdAt:
                type: datetime
            createdAtNullable?:
                type: datetime
            number:
                description: Test number description.
                type: integer
                format: long
            text:
                type: string
            textNullable?:
                type: string
            asset:
                type: common.Asset
