
#%RAML 1.0
title: Beta Annotation Test API
baseUri: https://example.com/{version}
version: v1
mediaType: application/json

annotationTypes:
  beta:
    type: boolean
    allowedTargets: [ TypeDeclaration ]

traits:
  priceSelecting:
    queryParameters:
      priceRecurrencePolicy?:
        type: string
        (beta): true
        description: |
          `id` of an existing RecurrencePolicy used for Product price selection.

/test:
  get:
    is: [ priceSelecting ]
    responses:
      200:
