#%RAML 1.0
title: Beta Annotation Regression Test API
baseUri: https://example.com/{version}
version: v1
mediaType: application/json

annotationTypes:
  beta:
    type: boolean
    allowedTargets: [ Method, Trait, TypeDeclaration ]

traits:
  priceSelecting:
    queryParameters:
      priceRecurrencePolicy?:
        type: string
        (beta): true
        description: |
          `id` of an existing RecurrencePolicy used for Product price selection.
  betaTrait:
    (beta): true
    description: a trait that marks any method using it as beta

/test:
  get:
    is: [ priceSelecting, betaTrait ]
    responses:
      200:
