/**
 *  Copyright 2021 Michael van Tellingen
 */
package io.vrap.codegen.languages.python

val pyGeneratedComment = """
    |# This file is automatically generated by the rmf-codegen project.
    |#
    |# The Python code generator is maintained by Lab Digital. If you want to
    |# contribute to this project then please do not edit this file directly
    |# but send a pull request to the Lab Digital fork of rmf-codegen at
    |# https://github.com/labd/rmf-codegen
    """.trimMargin()
