#%RAML 1.0
---
title: Commercetools Importer API
version: v1
mediaType: application/json
baseUri: https://import.commercetools.com

uses:
  error: types/error.raml
  import-item: types/import-item.raml
  import-sink: types/import-sink.raml
  price-import: types/price-import.raml
  product-import: types/product-import.raml
  product-type-import: types/product-type-import.raml
  product-variant-import: types/product-variant-import.raml
  category-import: types/category-import.raml
  common: types/common.raml
  unresolved-import-resource: types/unresolved-import-resource.raml
  price-mapping: types/price-mapping.raml

securitySchemes:
  oauth_2_0: !include security-schemes/oauth2.raml
securedBy: [ oauth_2_0 ]

/{projectKey}:
  uriParameters:
    projectKey:
      description: The CTP project key.
      type: string
  /import-sinks:
    post:
      description: Creates a new import sink.
      body:
        type: import-sink.ImportSinkDraft
      responses:
        201:
          body:
            type: import-sink.ImportSink
        400:
          description: The request was invalid.
          body:
            type: error.ErrorResponse
    /{importSinkKey}:
      uriParameters:
        key:
          description: The key of the import sink.
          type: string
      put:
        description: Updates the import sink given by the key.
        body:
          type: import-sink.ImportSinkDraft
        responses:
          200:
            description: The import sink was successfully updated.
            body:
              type: import-sink.ImportSink
          409:
            description: A concurrent modification was detected. The client should retry and resolve the conflict.
            body:
              type: error.ErrorResponse
      get:
        description: Retrieves the import sink given by the key.
        responses:
          200:
            description: The requested import sink was found.
            body:
              type: import-sink.ImportSink
          404:
            description: The requested import sink wasn't found.
            body:
              type: error.ErrorResponse
      delete:
        description: Deletes the import sink given by the key.
        responses:
          200:
            body:
              type: import-sink.ImportSink
      /requests:
        post:
          description: Creates a new import request.
          body:
            type: import-sink.ImportRequest
          responses:
            201:
              body:
                type: import-sink.ImportRequestState
      /items:
        get:
          queryParameters:
            limit?:
              type: number
            offset?:
              type: number
          description: Retieves all import items of an import sink key
          responses:
            200:
              body:
                type: import-item.ImportItemPagedResponse
        /{resourceKey}:
          get:
            description: Retrieves inidividual import items for the given resource and import sink.
            responses:
              200:
                body:
                  type: import-item.ImportItem
