#%RAML 1.0
---
title: Commercetools API Test
version: v1
mediaType: application/json
baseUri: https://import.commercetools.com

uses:
    simple-type: types/simple-type.raml
    common: types/common.raml
