#%RAML 1.0 Library
usage: Import item types.
(generator.package): importitems

uses:
  common: common.raml
  error: error.raml
  generator: ../annotationTypes/generator.raml

types:
  ImportItem:
    description: This type represents an import item.
    properties:
      version:
        description: The import item version.
        type: integer
        format: long
      importSinkKey:
        description: The key of the import sink.
        type: string
      resourceKey:
        description: The key of the imported resource.
        type: string
      state:
        description: |
          The status of a single import request.
        type: common.ProcessingState
      retryCount:
        description: The number of retries for this item.
        type: number
      errors?:
        description: Used to report errors when an import item is in the state VALIDATION_FAILED or REJECTED.
        type: error.ErrorObject[]
      createdAt:
        description: The creation time of this import item.
        type: datetime
      lastModifiedAt:
        description: The last modification time of this import item.
        type: datetime
    examples:
      accepted:        !include ../examples/accepted-import-item.json
      validationFailed: !include ../examples/validation-failed-import-item.json
  ImportItemPagedResponse:
    description: This type represents a paged import item result.
    properties:
      limit:
        description: The maximun amount of impor items.
        type: number
      offset:
        description: The offset supplied by the client or the server default. It is the number of elements skipped.
        type: number
      count:
        description: The actual number of results returned in results.
        type: number
      total:
        description: The total number of results matching the query.
        type: number
      results:
        description: An Array of results.
        type: ImportItem[]


