#%RAML 1.0 Library
usage: The unresolved resources types.
(generator.package): importresources

uses:
  common: common.raml
  generator: ../annotationTypes/generator.raml

types:
  UnresolvedImportResource:
    description: This type represents a resource with on or more unresolved references.
    properties:
      resourceKey:
        description: The key of the imported resource.
        type: string
      resourceType:
        description: The type of the imported resource.
        type: common.ResourceType
      resourceAsString:
        description: the resource which could not successfull imported
        type: string
      importSinkKey?:
        description: the key of the import sink
        type: string
      createdAt:
        description: The creation time of this import item.
        type: datetime
      lastModifiedAt:
        description: The last modification time of this import item.
        type: datetime
