#%RAML 1.0
title: method response type change

types:
  Foo:
    type: object
    properties:
      foo: object
  Bar:
    type: Foo

/foo:
  get:
    responses:
      200:
        body:
          application/json:
            type: Bar
          application/text:
            type: Foo
