#%RAML 1.0 Library
usage: Error types.
(generator.package): errors

uses:
  generator: ../annotationTypes/generator.raml
  product-variant-import: product-variant-import.raml
  price-import: price-import.raml

types:
  ErrorResponse:
    properties:
        statusCode:
            type: integer
        message:
            type: string
        error?:
            type: string
        error_description?:
            type: string
        errors?:
            type: ErrorObject[]
  ErrorObject:
    discriminator: code
    properties:
        code:
            type: string
        message:
            type: string
  AccessDeniedError:
    type: ErrorObject
    discriminatorValue: access_denied
  DuplicateAttributeValueError:
    type: ErrorObject
    discriminatorValue: DuplicateAttributeValue
    properties:
      attribute:
        type: product-variant-import.Attribute
  DuplicateAttributeValuesError:
    type: ErrorObject
    discriminatorValue: DuplicateAttributeValues
    properties:
      attributes:
        type: product-variant-import.Attribute[]
  DuplicateFieldError:
    type: ErrorObject
    discriminatorValue: DuplicateField
    properties:
      field?:
        type: string
      duplicateValue?:
        type: any
  DuplicateVariantValuesError:
    type: ErrorObject
    discriminatorValue: DuplicateVariantValues
    properties:
      variantValues:
        type: VariantValues
  VariantValues:
    properties:
      sku?:
        type: string
      prices:
        type: price-import.PriceImport[]
      attributes:
        type: product-variant-import.Attribute[]
  InsufficientScopeError:
    type: ErrorObject
    discriminatorValue: insufficient_scope
  InvalidCredentialsError:
    type: ErrorObject
    discriminatorValue: InvalidCredentials
  InvalidTokenError:
    type: ErrorObject
    discriminatorValue: invalid_token
  InvalidFieldError:
    type: ErrorObject
    discriminatorValue: InvalidField
    properties:
      field:
          type: string
      invalidValue:
          type: any
      allowedValues?:
          type: any[]
  ResourceNotFoundError:
    type: ErrorObject
    discriminatorValue: ResourceNotFound
  RequiredFieldError:
    type: ErrorObject
    discriminatorValue: RequiredField
    properties:
      field:
        type: string

