on:
  - workflow_dispatch
  - push

name: CI

permissions: {}

jobs:
  test:
    name: Build and test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build and Release
        run: ./gradlew clean check shadowJar

      - run: ./scripts/install_local.sh
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: test
          persist-credentials: 'false'

      - name: Test validate
        continue-on-error: true
        run: rmf-codegen validate -f GITHUB -r ./api-spec/ruleset.xml ./api-spec/api.raml
        working-directory: test
  test_node:
    name: Build npm package

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "14"

      - name: Build npm package
        working-directory: node/rmf-codegen
        run: yarn build

      - name: Run npm package
        working-directory: node/rmf-codegen
        run: node bin/rmf-codegen.js
