on:
  push:
    branches:
      - master

name: AutoRelease (BinTray)

jobs:
  release:
    name: Build and release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "8"

      - name: Build and Test
        run: ./gradlew --build-cache clean check

      - name: Release
        run: ./gradlew --build-cache bintrayUpload writeVersionToReadme --info --stacktrace
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}

      - uses: stefanzweifel/git-auto-commit-action@v4.6.0
        with:
          commit_message: "TASK: Updating version in README"
          commit_user_name: Auto Mation
          commit_user_email: automation@commercetools.com
          commit_author: Auto Mation <automation@commercetools.com>
