on:
  - workflow_dispatch
  - push

name: CI


jobs:
  test:
    name: Build and test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build and Release
        run: ./gradlew clean check shadowJar

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: test

      - name: Test validate
        continue-on-error: true
        run: ./rmf-gen.sh validate -f GITHUB ./api-spec/api.raml
        working-directory: test
  test_node:
    name: Build npm package

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Build npm package
        working-directory: node/rmf-codegen
        run: yarn build

      - name: Run npm package
        working-directory: node/rmf-codegen
        run: node bin/rmf-codegen.js
