#%RAML 1.0 Library
usage: Common data types.
(generator.package): common

uses:
  generator: ../annotationTypes/generator.raml

types:
  Asset:
    properties:
        id:
            type: string
        sources:
            type: AssetSource[]
        name:
            type: LocalizedString
        description?:
            type: LocalizedString
        tags?:
            type: string[]
  AssetDimensions:
    properties:
        w:
            type: number
        h:
            type: number
  AssetSource:
    properties:
        uri:
            type: string
        key?:
            type: string
        dimensions?:
            type: AssetDimensions
        contentType?:
            type: string
  CountryCode:
    type: string
    description: |
      A two-digit country code as per [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
    pattern: ^[A-Z]{2}$
  CurrencyCode:
    type: string
    description: |
      The currency code compliant to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).
    pattern: ^[A-Z]{3}$
  Image:
    properties:
        url:
            type: string
        dimensions:
            type: AssetDimensions
        label?:
            type: string
  EnumValue:
    properties:
      key:
        type: string
      label:
        type: string
  LocalizedEnumValue:
    properties:
      key:
        type: string
      label:
        type: LocalizedString
  LocalizedString:
    (generator.asMap):
      keyTypeHint: common.CountryCode
    type: object
    properties:
      /^[a-z]{2}(-[A-Z]{2})?$/:
        type: string
  ImportResource:
    description: An import resource is identified by a key. This type is the base type of all import resources.
    properties:
      key: string
  ImportReference:
    description: An import reference references a resource by its key.
    properties:
      key: string
  Money:
    properties:
        centAmount:
            type: number
            format: int64
        currencyCode:
            type: CurrencyCode
  ResourceType:
    type: string
    enum:
      - CATEGORY
      - PRICE
      - PRODUCT
      - PRODUCT_TYPE
      - PRODUCT_VARIANT
      - TAX_CATEGORY
      - STATE

annotationTypes:
  ReferenceType:
    description: |
      This annotation documents the type of an import reference.
    type: string
    enum:
      - CATEGORY
      - PRICE
      - PRODUCT
      - PRODUCT_TYPE
      - PRODUCT_VARIANT
      - TAX_CATEGORY
      - STATE
